{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOpcqrRorf0rTuiREcATn8h",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/taylorns-git/portfolio/blob/main/Gradebook.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "import csv\n",
        "\n",
        "grades = []\n",
        "\n",
        "def add_grade():\n",
        "    print('\\n= Add New Grade =')\n",
        "\n",
        "    student = input('Student name: ')\n",
        "    subject = input('Class subject: ')\n",
        "\n",
        "    # Loop to ensure the user enters a valid number for the grade.\n",
        "    while True:\n",
        "        try:\n",
        "            grade = float(input('Enter grade: '))\n",
        "\n",
        "            if grade < 0:\n",
        "                print('Grade cannot be negative. Please try again.')\n",
        "            else:\n",
        "                break\n",
        "        except ValueError:\n",
        "            print('Invalid grade. Please enter a numeric value.')\n",
        "\n",
        "    # Create a dictionary to hold the details of the new grade.\n",
        "    gradebook = {\n",
        "        'student': student,\n",
        "        'subject': subject,\n",
        "        'grade': grade,\n",
        "    }\n",
        "\n",
        "    # Add the newly created grade dictionary to the global grades list.\n",
        "    grades.append(gradebook)\n",
        "    print('Grade added successfully!')\n",
        "\n",
        "def view_grades():\n",
        "    print('\\n= View Grades = ')\n",
        "\n",
        "    if not grades:\n",
        "        print('No grades found yet. Add some grades first!')\n",
        "        return\n",
        "\n",
        "    for gradebook in grades:\n",
        "        student = gradebook['student']\n",
        "        subject = gradebook['subject']\n",
        "        grade = gradebook['grade']\n",
        "\n",
        "        print(f'Student {student} | Subject {subject} | Grade {grade:.2f}')\n",
        "\n",
        "def save_grades():\n",
        "    if not grades:\n",
        "        print('No grades to save.')\n",
        "        return\n",
        "\n",
        "    print('\\nSaving grades to gradebook.csv...')\n",
        "\n",
        "    with open('gradebook.csv', 'w', newline='') as file:\n",
        "\n",
        "        fieldnames = ['student', 'subject', 'grade']\n",
        "\n",
        "        writer = csv.DictWriter(file, fieldnames=fieldnames)\n",
        "\n",
        "        writer.writeheader()\n",
        "        writer.writerows(grades)\n",
        "    print('Grades saved successfully to gradebook.csv!')\n",
        "\n",
        "def load_grades():\n",
        "    global grades\n",
        "    print('\\nLoading grades from gradebook.csv.')\n",
        "\n",
        "    if os.path.exists('gradebook.csv'):\n",
        "        grades.clear()\n",
        "        with open('gradebook.csv', 'r', newline='') as file:\n",
        "            reader = csv.DictReader(file)\n",
        "            for row in reader:\n",
        "                try:\n",
        "                    row['grade'] = float(row['grade'])\n",
        "                    grades.append(row)\n",
        "                except ValueError:\n",
        "                    print(f'Warning: could not convert grade for row: {row}.')\n",
        "        print(f'Successfully loaded {len(grades)} grades from gradebook.csv.')\n",
        "    else:\n",
        "        print('No grades file (gradebook.csv) found, starting with an empty grade.')\n",
        "\n",
        "def main_menu():\n",
        "    # Automatically load grades.\n",
        "    load_grades()\n",
        "\n",
        "\n",
        "    while True:\n",
        "        print('\\n= Gradebook menu =')\n",
        "        print('1. Add New Grade')\n",
        "        print('2. View Grades')\n",
        "        print('3. Save Grades')\n",
        "        print('4. Exit')\n",
        "\n",
        "        choice = input('Enter your choice: ')\n",
        "\n",
        "        if choice == '1':\n",
        "            add_grade()\n",
        "        elif choice == '2':\n",
        "            view_grades()\n",
        "        elif choice == '3':\n",
        "            save_grades()\n",
        "        elif choice == '4':\n",
        "            print('Exiting Gradebook. Goodbye!')\n",
        "            save_grades()\n",
        "            break\n",
        "        else:\n",
        "            print('Invalid choice. Please try again.')\n",
        "\n",
        "if __name__ == '__main__':\n",
        "    main_menu()"
      ],
      "metadata": {
        "id": "BuC39TZg-SGN"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}