{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPjv57dOusoW1qEPwbRh+YW",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/taylorns-git/portfolio/blob/main/Personal_Expense_Tracker.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "6602eadd"
      },
      "source": [
        "import os\n",
        "import csv\n",
        "\n",
        "# --- Global Variables --- #\n",
        "# This list will store all expense dictionaries. Each dictionary represents a single expense.\n",
        "expenses = []\n",
        "# This variable will store the user's monthly budget, initialized to 0.0.\n",
        "monthly_budget = 0.0\n",
        "\n",
        "# --- Expense Management Functions --- #\n",
        "\n",
        "# Function to add a new expense.\n",
        "def add_expense():\n",
        "  print('\\n--- Add New Expense ---')\n",
        "  # Get date, category, and description from the user.\n",
        "  date = input('Enter date (YYYY-MM-DD): ')\n",
        "  category = input('Enter category (e.g., Food, Travel, Utilities): ')\n",
        "\n",
        "  # Loop to ensure the user enters a valid number for the amount.\n",
        "  while True:\n",
        "    try:\n",
        "      amount = float(input('Enter amount spent: $'))\n",
        "      # Ensure amount is not negative\n",
        "      if amount < 0:\n",
        "        print('Amount cannot be negative. Please enter a positive value.')\n",
        "      else:\n",
        "        break # Exit loop if a valid non-negative amount is entered\n",
        "    except ValueError:\n",
        "      print('Invalid amount. Please enter a numeric value (e.g., 25.50).')\n",
        "\n",
        "  description = input('Enter a short description: ')\n",
        "\n",
        "  # Create a dictionary to hold the details of the new expense.\n",
        "  expense = {\n",
        "      'date': date,\n",
        "      'category': category,\n",
        "      'amount': amount,\n",
        "      'description': description,\n",
        "  }\n",
        "\n",
        "  # Add the newly created expense dictionary to the global 'expenses' list.\n",
        "  expenses.append(expense)\n",
        "  print('Expense added successfully!')\n",
        "\n",
        "# Function to display all recorded expenses.\n",
        "def view_expenses():\n",
        "  print('\\n--- Your Expenses ---')\n",
        "\n",
        "  # Check if the 'expenses' list is empty. If so, inform the user.\n",
        "  if not expenses:\n",
        "    print('No expenses found yet. Add some expenses first!')\n",
        "    return\n",
        "\n",
        "  # Iterate through each expense dictionary in the 'expenses' list.\n",
        "  for expense in expenses:\n",
        "    # Extract details from the current expense dictionary.\n",
        "    date = expense['date']\n",
        "    category = expense['category']\n",
        "    amount = expense['amount']\n",
        "    description = expense['description']\n",
        "\n",
        "    # Print the details of each expense in a formatted way.\n",
        "    print(f'{date} | Category: {category} | Amount: ${amount:.2f} | Description: {description}')\n",
        "\n",
        "# --- Budget Management Functions --- #\n",
        "\n",
        "# Function to allow the user to set or update their monthly budget.\n",
        "def set_monthly_budget():\n",
        "  global monthly_budget # Declare 'monthly_budget' as global to modify the global variable.\n",
        "  print('\\n--- Set Monthly Budget ---')\n",
        "  while True:\n",
        "    try:\n",
        "      new_budget = float(input('Enter your desired monthly budget: $'))\n",
        "      # Ensure the budget is not negative.\n",
        "      if new_budget >= 0:\n",
        "        monthly_budget = new_budget\n",
        "        print(f'Monthly budget successfully set to ${monthly_budget:.2f}.')\n",
        "        break # Exit loop if a valid non-negative budget is entered.\n",
        "      else:\n",
        "        print('Budget cannot be negative. Please enter a positive value.')\n",
        "    except ValueError:\n",
        "      print('Invalid input. Please enter a numeric value for the budget (e.g., 1000.00).')\n",
        "\n",
        "# Function to track expenses against the set budget.\n",
        "def track_budget():\n",
        "  print('\\n--- Budget Tracker ---')\n",
        "\n",
        "  # Check if a monthly budget has been set. If not, prompt the user.\n",
        "  if monthly_budget <= 0:\n",
        "    print('No monthly budget set. Please set a budget first using option 6.')\n",
        "    return\n",
        "\n",
        "  # Calculate the total amount spent from all recorded expenses.\n",
        "  total_expenses = 0.0\n",
        "  for expense in expenses:\n",
        "    total_expenses += expense['amount'] # Add each expense amount to the total.\n",
        "\n",
        "  print(f'Total Expenses Incurred: ${total_expenses:.2f}')\n",
        "  print(f'Your Monthly Budget: ${monthly_budget:.2f}')\n",
        "\n",
        "  # Compare total expenses with the monthly budget and provide feedback.\n",
        "  if total_expenses > monthly_budget:\n",
        "    print(f'Alert! You have exceeded your budget by ${total_expenses - monthly_budget:.2f}.')\n",
        "  else:\n",
        "    print(f'Remaining Budget: ${monthly_budget - total_expenses:.2f}.')\n",
        "\n",
        "# --- File I/O Functions --- #\n",
        "\n",
        "# Function to save all current expenses to a CSV file.\n",
        "def save_expenses():\n",
        "  # Only save if there are expenses to save.\n",
        "  if not expenses:\n",
        "    print('No expenses to save.')\n",
        "    return\n",
        "\n",
        "  print('\\nSaving expenses to expenses.csv...')\n",
        "  # Open 'expenses.csv' in write mode ('w'). 'newline=' prevents extra blank rows.\n",
        "  # 'with open(...)' ensures the file is properly closed even if errors occur.\n",
        "  with open('expenses.csv', 'w', newline='') as file:\n",
        "    # Define the column headers for the CSV file.\n",
        "    fieldnames = ['date', 'category', 'amount', 'description']\n",
        "    # Create a DictWriter object to write dictionaries to the CSV file.\n",
        "    writer = csv.DictWriter(file, fieldnames=fieldnames)\n",
        "\n",
        "    writer.writeheader() # Write the header row to the CSV.\n",
        "    writer.writerows(expenses) # Write all expense dictionaries as rows.\n",
        "  print('Expenses saved successfully to expenses.csv!')\n",
        "\n",
        "# Function to load expenses from a CSV file into the 'expenses' list.\n",
        "def load_expenses():\n",
        "  global expenses # Declare 'expenses' as global to modify the global list.\n",
        "  print('\\nLoading expenses from expenses.csv...')\n",
        "  # Check if the 'expenses.csv' file exists before trying to open it.\n",
        "  if os.path.exists('expenses.csv'):\n",
        "    # Clear any existing expenses in the list before loading new ones.\n",
        "    expenses.clear()\n",
        "    with open('expenses.csv', 'r', newline='') as file:\n",
        "      # Create a DictReader object to read rows as dictionaries from the CSV.\n",
        "      reader = csv.DictReader(file)\n",
        "      # Iterate over each row (which is a dictionary) in the CSV file.\n",
        "      for row in reader:\n",
        "        try:\n",
        "          # Convert the 'amount' back to a float, as it's read as a string from CSV.\n",
        "          row['amount'] = float(row['amount'])\n",
        "          expenses.append(row) # Add the loaded expense to the global list.\n",
        "        except ValueError:\n",
        "          # Handle cases where 'amount' in the CSV might not be a valid number.\n",
        "          print(f\"Warning: Could not convert amount for row: {row}. Skipping this entry.\")\n",
        "    print(f'Successfully loaded {len(expenses)} expenses from expenses.csv.')\n",
        "  else:\n",
        "    print('No expenses file (expenses.csv) found. Starting with an empty expense list.')\n",
        "\n",
        "# --- Main Program Flow --- #\n",
        "\n",
        "# The main function that runs the expense tracker application.\n",
        "def main_menu():\n",
        "  # Automatically load expenses when the program starts to restore previous data.\n",
        "  load_expenses()\n",
        "  global monthly_budget # Ensure we can access/modify the global monthly_budget.\n",
        "\n",
        "  # Main loop for the menu, runs until the user chooses to exit.\n",
        "  while True:\n",
        "    print('\\n--- Personal Expense Tracker Menu ---')\n",
        "    print('1. Add a New Expense')\n",
        "    print('2. View All Expenses')\n",
        "    print('3. Track Budget Progress')\n",
        "    print('4. Save Expenses to File')\n",
        "    print('5. Exit Program')\n",
        "\n",
        "    choice = input('Enter your choice (1-5): ')\n",
        "\n",
        "    # Use if/elif/else to perform actions based on user's choice.\n",
        "    if choice == '1':\n",
        "      add_expense()\n",
        "    elif choice == '2':\n",
        "      view_expenses()\n",
        "    elif choice == '3':\n",
        "      track_budget()\n",
        "    elif choice == '4':\n",
        "      save_expenses()\n",
        "    elif choice == '5':\n",
        "      # Before exiting, save the current expenses to prevent data loss.\n",
        "      print('Exiting the program.')\n",
        "      save_expenses()\n",
        "      break # Exit the while loop, ending the program.\n",
        "    else:\n",
        "      print('Invalid choice. Please enter a number between 1 and 5.')\n",
        "\n",
        "# Call the main menu function to start the application when the script is run.\n",
        "main_menu()\n"
      ],
      "execution_count": null,
      "outputs": []
    }
  ]
}